# RRRalgorithms Local Development Configuration
# This is the default configuration for local laptop development
# Optimized for low resource usage and fast iteration

environment: local
debug: true

# Database Configuration (SQLite for local)
database:
  type: sqlite
  path: data/local.db
  echo: false  # Set to true for SQL debugging
  pool_size: 5
  max_overflow: 10

# Cache Configuration (In-memory for local)
cache:
  type: memory
  ttl: 300  # 5 minutes
  max_size: 1000

# Data Pipeline Configuration
data_pipeline:
  mode: mock  # Options: mock, historical, live
  mock:
    enabled: true
    update_interval: 1.0  # seconds
    symbols: ["BTC-USD", "ETH-USD"]
    volatility: 0.02
  historical:
    enabled: false
    data_dir: data/samples
  live:
    enabled: false
    # Requires API keys in .env.local

# Trading Engine Configuration
trading:
  mode: paper  # Always paper for local
  exchange: mock
  initial_capital: 10000
  max_position_size: 0.20  # 20% of portfolio
  max_daily_loss: 0.05  # 5% stop
  order_timeout: 30  # seconds
  
# Risk Management
risk:
  enabled: true
  max_portfolio_volatility: 0.25
  max_drawdown: 0.15
  position_sizing: kelly  # kelly, fixed, volatility
  kelly_fraction: 0.5  # Half Kelly for safety

# Neural Network Configuration (Lightweight)
neural_network:
  mode: mock  # Options: mock, lightweight, full
  mock:
    enabled: true
    random_seed: 42
  lightweight:
    enabled: false
    model_type: sklearn  # sklearn, small_transformer
    feature_count: 20
    lookback_window: 30
  full:
    enabled: false
    # Requires requirements-full.txt

# Monitoring Configuration (Console-based)
monitoring:
  type: console  # console, file, none
  log_level: INFO
  log_file: logs/trading.log
  metrics:
    enabled: true
    update_interval: 5  # seconds
    console_refresh: 1  # seconds
  performance:
    track_trades: true
    track_metrics: true

# API Integrations (All optional for local)
apis:
  coinbase:
    enabled: false
    use_sandbox: true
  polygon:
    enabled: false
  perplexity:
    enabled: false

# Backtesting Configuration
backtesting:
  enabled: true
  data_source: csv
  csv_dir: data/samples
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  commission: 0.001  # 0.1%

# Service Configuration
services:
  run_mode: single_process  # single_process, separate_processes
  enabled_services:
    - data_pipeline
    - trading_engine
    - risk_management
    - monitoring
  disabled_services:
    - quantum_optimization  # Too resource intensive
    - mlflow  # Not needed for local

# Resource Limits (for laptop)
resources:
  max_memory_mb: 2048  # 2GB limit
  max_cpu_percent: 50  # Don't hog the CPU
  worker_threads: 2
  async_workers: 4

# Development Settings
development:
  auto_reload: true
  show_sql: false
  profile: false
  test_mode: false

