name: Worktree Tests

on:
  push:
    branches: [main, master, develop, feature/*]
  pull_request:
    branches: [main, master, develop]

jobs:
  detect-changes:
    name: Detect changed worktrees
    runs-on: ubuntu-latest
    outputs:
      data-pipeline: ${{ steps.filter.outputs.data-pipeline }}
      trading-engine: ${{ steps.filter.outputs.trading-engine }}
      neural-network: ${{ steps.filter.outputs.neural-network }}
      risk-management: ${{ steps.filter.outputs.risk-management }}
      backtesting: ${{ steps.filter.outputs.backtesting }}
      monitoring: ${{ steps.filter.outputs.monitoring }}
      quantum-optimization: ${{ steps.filter.outputs.quantum-optimization }}
      api-integration: ${{ steps.filter.outputs.api-integration }}

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            data-pipeline:
              - 'worktrees/data-pipeline/**'
            trading-engine:
              - 'worktrees/trading-engine/**'
            neural-network:
              - 'worktrees/neural-network/**'
            risk-management:
              - 'worktrees/risk-management/**'
            backtesting:
              - 'worktrees/backtesting/**'
            monitoring:
              - 'worktrees/monitoring/**'
            quantum-optimization:
              - 'worktrees/quantum-optimization/**'
            api-integration:
              - 'worktrees/api-integration/**'

  test-data-pipeline:
    name: Test Data Pipeline
    needs: detect-changes
    if: needs.detect-changes.outputs.data-pipeline == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: worktrees/data-pipeline
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-cov

      - name: Run tests
        working-directory: worktrees/data-pipeline
        run: |
          pytest tests/ --cov=src --cov-report=term-missing
        env:
          SUPABASE_URL: https://test.supabase.co
          SUPABASE_ANON_KEY: test_key
          POLYGON_API_KEY: test_key

  test-trading-engine:
    name: Test Trading Engine
    needs: detect-changes
    if: needs.detect-changes.outputs.trading-engine == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: worktrees/trading-engine
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-cov

      - name: Run tests
        working-directory: worktrees/trading-engine
        run: |
          pytest tests/ --cov=src --cov-report=term-missing
        env:
          SUPABASE_URL: https://test.supabase.co
          SUPABASE_ANON_KEY: test_key
          PAPER_TRADING: true

  test-monitoring:
    name: Test Monitoring
    needs: detect-changes
    if: needs.detect-changes.outputs.monitoring == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: worktrees/monitoring
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-cov

      - name: Run tests
        working-directory: worktrees/monitoring
        run: |
          pytest tests/ --cov=src --cov-report=term-missing || true
        env:
          SUPABASE_URL: https://test.supabase.co
          SUPABASE_ANON_KEY: test_key
